angular.module('myApp')
    .constant('jobType',JSON.parse(sessionStorage.getItem('jobType')))
    .constant('hotSearch',JSON.parse(sessionStorage.getItem('hotSearch')))
    .constant('arrival',JSON.parse(sessionStorage.getItem('arrival')))
    .constant('boon',JSON.parse(sessionStorage.getItem('boon')))
    .constant('expList',JSON.parse(sessionStorage.getItem('expList')))
    .constant('eduList',JSON.parse(sessionStorage.getItem('eduList')))
    .constant('bannerImg',JSON.parse(sessionStorage.getItem('bannerImg')))
    .constant('orderBy',[
        {name:"正序",value:0},
        {name:"倒序",value:1},
        ])
;